// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Application struct {
	ID        int64     `json:"id"`
	UserID    string    `json:"user_id"`
	Company   string    `json:"company"`
	Role      string    `json:"role"`
	Status    string    `json:"status"`
	Url       string    `json:"url"`
	Notes     string    `json:"notes"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Generation struct {
	ID             int64     `json:"id"`
	UserID         string    `json:"user_id"`
	Kind           string    `json:"kind"`
	JobTitle       string    `json:"job_title"`
	Company        string    `json:"company"`
	JobDescription string    `json:"job_description"`
	Output         string    `json:"output"`
	CreatedAt      time.Time `json:"created_at"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type User struct {
	ID            string     `json:"id"`
	Email         string     `json:"email"`
	CreatedAt     time.Time  `json:"created_at"`
	LastSeen      time.Time  `json:"last_seen"`
	Plan          string     `json:"plan"`
	PlanUntil     *time.Time `json:"plan_until"`
	BaseResume    string     `json:"base_resume"`
	ProfileNotes  string     `json:"profile_notes"`
	MonthlyCount  int64      `json:"monthly_count"`
	MonthlyPeriod string     `json:"monthly_period"`
}
