// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: visitors.sql

package dbgen

import (
	"context"
	"time"
)

const bumpMonthlyCount = `-- name: BumpMonthlyCount :exec
UPDATE users SET monthly_count = ?, monthly_period = ? WHERE id = ?
`

type BumpMonthlyCountParams struct {
	MonthlyCount  int64  `json:"monthly_count"`
	MonthlyPeriod string `json:"monthly_period"`
	ID            string `json:"id"`
}

func (q *Queries) BumpMonthlyCount(ctx context.Context, arg BumpMonthlyCountParams) error {
	_, err := q.db.ExecContext(ctx, bumpMonthlyCount, arg.MonthlyCount, arg.MonthlyPeriod, arg.ID)
	return err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications WHERE id = ? AND user_id = ?
`

type DeleteApplicationParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteApplication(ctx context.Context, arg DeleteApplicationParams) error {
	_, err := q.db.ExecContext(ctx, deleteApplication, arg.ID, arg.UserID)
	return err
}

const getGeneration = `-- name: GetGeneration :one
SELECT id, user_id, kind, job_title, company, job_description, output, created_at FROM generations WHERE id = ? AND user_id = ?
`

type GetGenerationParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetGeneration(ctx context.Context, arg GetGenerationParams) (Generation, error) {
	row := q.db.QueryRowContext(ctx, getGeneration, arg.ID, arg.UserID)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.JobTitle,
		&i.Company,
		&i.JobDescription,
		&i.Output,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, created_at, last_seen, "plan", plan_until, base_resume, profile_notes, monthly_count, monthly_period FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.LastSeen,
		&i.Plan,
		&i.PlanUntil,
		&i.BaseResume,
		&i.ProfileNotes,
		&i.MonthlyCount,
		&i.MonthlyPeriod,
	)
	return i, err
}

const insertApplication = `-- name: InsertApplication :one
INSERT INTO applications (user_id, company, role, status, url, notes, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, company, role, status, url, notes, created_at, updated_at
`

type InsertApplicationParams struct {
	UserID    string    `json:"user_id"`
	Company   string    `json:"company"`
	Role      string    `json:"role"`
	Status    string    `json:"status"`
	Url       string    `json:"url"`
	Notes     string    `json:"notes"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) InsertApplication(ctx context.Context, arg InsertApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, insertApplication,
		arg.UserID,
		arg.Company,
		arg.Role,
		arg.Status,
		arg.Url,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Company,
		&i.Role,
		&i.Status,
		&i.Url,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGeneration = `-- name: InsertGeneration :one
INSERT INTO generations (user_id, kind, job_title, company, job_description, output, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, kind, job_title, company, job_description, output, created_at
`

type InsertGenerationParams struct {
	UserID         string    `json:"user_id"`
	Kind           string    `json:"kind"`
	JobTitle       string    `json:"job_title"`
	Company        string    `json:"company"`
	JobDescription string    `json:"job_description"`
	Output         string    `json:"output"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) InsertGeneration(ctx context.Context, arg InsertGenerationParams) (Generation, error) {
	row := q.db.QueryRowContext(ctx, insertGeneration,
		arg.UserID,
		arg.Kind,
		arg.JobTitle,
		arg.Company,
		arg.JobDescription,
		arg.Output,
		arg.CreatedAt,
	)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.JobTitle,
		&i.Company,
		&i.JobDescription,
		&i.Output,
		&i.CreatedAt,
	)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT id, user_id, company, role, status, url, notes, created_at, updated_at FROM applications WHERE user_id = ? ORDER BY updated_at DESC
`

func (q *Queries) ListApplications(ctx context.Context, userID string) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, listApplications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Company,
			&i.Role,
			&i.Status,
			&i.Url,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenerations = `-- name: ListGenerations :many
SELECT id, user_id, kind, job_title, company, job_description, output, created_at FROM generations WHERE user_id = ? ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListGenerations(ctx context.Context, userID string) ([]Generation, error) {
	rows, err := q.db.QueryContext(ctx, listGenerations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Generation{}
	for rows.Next() {
		var i Generation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.JobTitle,
			&i.Company,
			&i.JobDescription,
			&i.Output,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBaseResume = `-- name: SetBaseResume :exec
UPDATE users SET base_resume = ?, profile_notes = ? WHERE id = ?
`

type SetBaseResumeParams struct {
	BaseResume   string `json:"base_resume"`
	ProfileNotes string `json:"profile_notes"`
	ID           string `json:"id"`
}

func (q *Queries) SetBaseResume(ctx context.Context, arg SetBaseResumeParams) error {
	_, err := q.db.ExecContext(ctx, setBaseResume, arg.BaseResume, arg.ProfileNotes, arg.ID)
	return err
}

const setPlan = `-- name: SetPlan :exec
UPDATE users SET plan = ?, plan_until = ? WHERE id = ?
`

type SetPlanParams struct {
	Plan      string     `json:"plan"`
	PlanUntil *time.Time `json:"plan_until"`
	ID        string     `json:"id"`
}

func (q *Queries) SetPlan(ctx context.Context, arg SetPlanParams) error {
	_, err := q.db.ExecContext(ctx, setPlan, arg.Plan, arg.PlanUntil, arg.ID)
	return err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :exec
UPDATE applications SET status = ?, notes = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdateApplicationStatusParams struct {
	Status    string    `json:"status"`
	Notes     string    `json:"notes"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        int64     `json:"id"`
	UserID    string    `json:"user_id"`
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateApplicationStatus,
		arg.Status,
		arg.Notes,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, email, created_at, last_seen)
VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  email = excluded.email,
  last_seen = excluded.last_seen
`

type UpsertUserParams struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.ID,
		arg.Email,
		arg.CreatedAt,
		arg.LastSeen,
	)
	return err
}
